In [ ]:
!pip install wikipedia
!pip install nltk
!pip install scikit-learn
import wikipedia
import nltk
from nltk.corpus import stopwords
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer

  Preparing metadata (setup.py) ... done
  Created wheel for wikipedia: filename=wikipedia-1.4.0-py3-none-any.whl size=11678 sha256=b49b87abe925aaec409062b4cb48baa4e3a79a1133fa79dbeeba49694341176d
  Stored in directory: /root/.cache/pip/wheels/5e/b6/c5/93f3dec388ae76edc830cb42901bb0232504dfc0df02fc50de
Successfully built wikipedia


In [21]:
CORPUS = [
'No dia 16/02 recebo um e-mail da Loja alegando divergência de dados e acusando pagamento não autorizado! Sem nenhum detalhe adicional! Simplesmente negam a compra, a fatura permanece, e não explicam nada!Liguei para o atendimento e tive a mesma informação. Fui bem atendido. Como trabalho muito com notebook, realizei novamente a compra e fui informado que o pagamento é estornado em até 48h. Quando entrei no Reclame Aqui, que arrependimento tive! Reclamações de pessoas que há mais de uma semana não recebem o estorno, e de problemas similares ao meu! Espero sinceramente que o valor seja estornado logo e que a segunda compra seja bem procedida, e o produto entregue em tempo. Não tenho nenhum apreço por ter que recorrer a medidas legais! Espero profissionalismo e transparência da empresa, como obrigação com o consumidor!',
'Boa tarde, fiz um pedido de dois pneus dia 16/01/2020, quase na mesma hora recebi um e-mail de confirmação do pagamento, que a mercadoria já estava com a transportadora e que a previsão de retirada seria em até 7 dias úteis, achei ótimo, muito rápido, já que seria para colocar no carro para viajar no começo do mês, então fiquei muito satisfeito, ia dar tudo certo! Mais não foi isso q aconteceu, não recebi o e-mail de confirmação até a presente data, ai começou a dor de cabeça, mandei e-mail reclamando da demora do dito cujo e-mail de aprovação para retirada do produto no dia 31-01-2020 sendo q o prazo já tinha passado, a resposta foi a seguinte...Identificamos um problema operacional que atrasou a entrega do seu pedido 281425025, mas já estamos em contato com a transportadora para resolvermos o mais rápido possível.Não se preocupe, acionamos nossa equipe de suporte pelo protocolo 6803089. Já estamos acompanhando todo o processo e retornaremos o contato em 05 (cinco) dias úteis.Pedimos desculpas pelo transtorno e estamos à sua disposição.Protocolo: 6779662 Atenciosamente,Atendimento.com. Pois é a o prazo passou e ninguém entrou em contato, foi aí que mandei outro e-mail, e a resposta já foi outra de três dias.. Já acionamos a área responsável. Não se preocupe, em 03 (três) dias corridos o setor responsável entrará em contato.Pois bem ninguém entrou em contato, mas eu entrei em contato por telefone e quem me atendeu, falou em mais 5 dias para o contato comigo! Pow tá de brincadeira né , até quando isso?! Pior de tudo, é que eles tem o produto na loja, antes de comprar no site, passei na loja, mas estava bem mais caro, então optei por comprar no site e retirar na loja! Porém só libera a retirada do produto, com o e-mail de confirmação do site. Estou indignado com isso, pois já estou pagando o pneu no cartão, sendo que não tenho o produto em mãos.',
'Realizei a compra de 4 pneus no dia 21 de janeiro, e escolhi a opção de retirar na loja física, o prazo era de 7 dias. Até hoje não recebi a mercadoria, já liguei incontáveis vezes para o numero do atendimento e não obtenho nenhum tipo de retorno, no começo me falavam que eu tinha que aguardar o e-mail de confirmação para retirada da mercadoria na loja, e agora, quase um mês depois, a única coisa que me falam é que irão verificar e me retornar, mas não me retornam. No dia 05 de fevereiro recebi do atendimento@atendimento.com.br um e-mail (ANEXO) falando que iriam analisar o que aconteceu com o meu pedido e entrariam em contato dentro de 5 dias úteis, pois bem, estou até hoje aguardando e nada. Ontem fui na loja física e me informaram que não podem fazer nada, e que estão aguardando a transportadora. Saindo de lá liguei novamente no telefone do atendimento e fui informada pela atendente que a mercadoria havia voltado para o centro de distribuição pois não havia sido retirada. Em momento algum eu recebi e-mail que a mercadoria estava disponível para retirada, muito pelo contrário, todas as vezes que liguei me falaram que eu tinha que aguardar o e-mail. Inclusive quando fui na loja física a atendente não me informou que a mercadoria já tinha ido pra loja e retornado para o centro de distribuição, ela me disse que estava aguardando a transportadora e que não podia fazer absolutamente nada. É UM TOTAL DESCASO E FALTA DE RESPEITO COM O CONSUMIDOR, FICAMOS SEM RETORNO E AINDA RECEBEMOS INFORMAÇÕES DESENCONTRADAS, NINGUÉM RESOLVE O PROBLEMA, FALAM QUE IRÃO VERIFICAR E RETORNAR MAS NÃO RETORNAM. É A PRIMEIRA E SERÁ A ÚLTIMA VEZ QUE COMPRO NO SITE da Loja, VOCÊS SÃO PÉSSIMOS. ATENDIMENTO HORRÍVEL. COMPREI COM VOCÊS POR CONTA DO PRAZO QUE ESTAVA NO SITE DE VOCÊS POIS TINHA VIAGEM MARCADA, E OLHA SÓ, NÃO CONSEGUI VIAJAR POIS OS PNEUS NÃO CHEGARAM A TEMPO. COMPRAR COM VOCÊS É SÓ PREJUÍZO, NÃO RECOMENDO PARA NINGUÉM.',
'No dia 11/02/2020 realizei um pedido de compras on-line no site da Loja. Na tela principal aparece uma promoção do creme dental siga sorrindo, no banner está escrito: compre 3 produtos do creme dental e concorra a R$1000,00* + FRETE GRÁTIS NAS COMPRAS ACIMA DE 39,90. Clicando no banner não existe nenhum regulamento nem mais informações, desta forma inclui na minha compra 3 produtos do creme dental no carrinho e no mesmo momento o valor do frete passou para 0 reais. Conclui a compra no valor de R$391,78 e quando foi cobrado no cartão haviam incluído o frete de R$14,90. As compras chegaram certas e resolvi fazer outro pedido (n 308435373). Ainda constava o mesmo banner de promoção então inclui os 3 produtos do creme dental. Novamente ocorreu o mesmo erro e o frete foi cobrado. Liguei no SAC (protocolo 6918522) e o atendente  me falou que na verdade ao comprar os 3 produtos do creme dental estaria concorrendo aos R$1000,00 da promoção e também concorrendo a um frete grátis. Argumentei que isso era uma propaganda enganosa, pois não estava claro a nenhum momento e não teria lógica participar de um sorteio para ganhar frete grátis!?!Recebi estas segundas compras certas, porém não obedeceram o horário escolhido no site e entregaram 1h antes do combinado, por sorte tinha alguém para receber naquele momento.Entrando no site da promoção do creme dental, existe sim a inclusão dos 3 produtos para concorrer aos R$1000,00 porém não existe nada sobre frete grátis muito menos vinculado aoà Loja. Desta forma solicito a devolução do valor dos fretes.'
]
new_doc = ['fiz uma compra dia 17/01/2020 e solicitei o máximo de parcelas no caso 15x, ai fui conferir e vi que foi parcelado apenas em 8x, liguei logo depois de 2h pra verificar e solicitar que fosse alterado para 15x assim como eu tinha solicitada, me comunicaram que eu teria que cancelar e fazer novamente a compra, até ai tudo bem eu solicitei o cancelamento com eles para comprar novamente, porém já se passaram 27 dias apás a solicitação do estorno do cartão de crédito, já efetuei várias ligações com dois protocolos em mãos e nada de ser feito o estorno, tive que pagar a primeira parcela que foi lançada na fatura e nada deles estornarem meu cartão, a segunda parcela já esta por vir e nada de estornarem a compra ou liberarem o limite do meu cartão.']

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
import pandas as pd
import numpy as np
import scipy.sparse as sp
from numpy.linalg import norm

def bagOfWords(corpus, ngram_range=(1,1)):
    vectorizer = CountVectorizer(min_df=1, ngram_range=ngram_range)
    caracteristicas = vectorizer.fit_transform(corpus)
    return vectorizer, caracteristicas

bow_vectorizer, bow_caracteristicas = bagOfWords(CORPUS)
caracteristicas = bow_caracteristicas.todense()
print (caracteristicas)

new_doc_caracteristicas = bow_vectorizer.transform(new_doc)
new_doc_caracteristicas = new_doc_caracteristicas.todense()
print (new_doc_caracteristicas)

feature_names = bow_vectorizer.get_feature_names_out()
print (feature_names)

#Para apresentar as caracteristicas do texto em forma de dateframe
def display_caracteristicas(caracteristicas, feature_names):
    df = pd.DataFrame(data=caracteristicas,
                      columns=feature_names)
    print (df)
    df.to_csv("saida.csv", encoding='utf-8')

display_caracteristicas(caracteristicas, feature_names)


def tfidf_transformer(bow_matrix):
    transformer = TfidfTransformer(norm='l2', smooth_idf=True, use_idf=True)
    tfidf_matrix = transformer.fit_transform(bow_matrix)
    return transformer, tfidf_matrix



feature_names = bow_vectorizer.get_feature_names_out()
#Para construir um tfidf
# Para construir o transformador do tfidf e mostrar o corpus das caracteristicas tfidf
tfidf_trans, tdidf_caracteristicas = tfidf_transformer(bow_caracteristicas)
caracteristicas = np.round(tdidf_caracteristicas.todense(), 2)
display_caracteristicas(caracteristicas, feature_names)
nd_tfidf = tfidf_trans.transform(new_doc_caracteristicas).np.asarray
nd_caracteristicas = np.round(nd_tfidf.todense(), 2)
display_caracteristicas(nd_caracteristicas, feature_names)
feature_names = bow_vectorizer.get_feature_names()

# Para calcular a frequencia de cada termo
tf = bow_caracteristicas.todense()
tf = np.array(tf, dtype='float64')
#Para exibir as frequencias
display_caracteristicas(tf, feature_names)

df = np.diff(sp.csc_matrix(bow_caracteristicas, copy=True).indptr)
df = 1 + df #Para normalizar os resultados do idf

display_caracteristicas([df], feature_names)


#Para calcular a frequencia inversa dos documentos (idf)
total_docs = 1 + len(CORPUS)
idf = 1.0 + np.log(float(total_docs) / df)

display_caracteristicas([np.round(idf, 2)], feature_names)

#Para calcular a matriz diagonal do idf
total_caracteristicas = bow_caracteristicas.shape[1]
idf_diag = sp.spdiags(idf, diags=0, m=total_caracteristicas, n=total_caracteristicas)
idf = idf_diag.todense()

print (np.round(idf, 2))

# Para calcular a matriz de termo frequencia do tfidf
tfidf = tf * idf
#Para apresentar a matriz com as caracteristicas tfidf
display_caracteristicas(np.round(tfidf, 2), feature_names)

# Minimos quadrados
norms = norm(tfidf, axis=1)
#Para normalizar a diferenca em cada documento por meio dos minimos quadrados
print("Minimos quadrados: ",np.round(norms, 2))

#Calcula a normalizacao para o tfidf
norm_tfidf = tfidf / norms[:, None]
#Apresenta a matriz final com o resultado do tfidf
display_caracteristicas(np.round(norm_tfidf, 2), feature_names)



[[0 0 1 ... 0 0 0]
 [0 2 0 ... 0 0 2]
 [0 0 0 ... 1 1 1]
 [3 0 1 ... 0 0 0]]
[[0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 3 0
  0 0 0 0 0 0 0 0 0 2 0 0 0 0 1 3 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 5 0 0 0 1 0 0 0 0 0 0 1 1 0 0 0 0 0 0 3 1 0 0 0 1 2 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 3 0 0 0 0 0 0 0 0 1 1 0 0 0 1 2
  0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 3 0 0
  1 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 2 0 0 0 1 0 1 3 0 0 0 0 0 0 1 0 0 2 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1
  0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 6 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 1 0 0 1 0
  0 1 0 0 0 0 0 0 0 0 0 0 0 0]]
['00' '01' '02' '03' '05' '1000' '11' '14' '16' '1h' '2020' '21'
 '281425025'

TypeError: ignored